# Generated by Django 5.2.5 on 2025-09-10 03:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_userprofile_delete_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="Profile",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="notes",
            new_name="note",
        ),
    ]
