# Generated by Django 5.2.5 on 2025-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_course_enrollment_questionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
