# Generated by Django 5.2.5 on 2025-09-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=20000),
        ),
    ]
