# Generated by Django 5.2.5 on 2025-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_course_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
