# Generated by Django 5.2.5 on 2025-09-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_profile_is_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"permissions": [("can_delete_user", "Can delete user")]},
        ),
    ]
